### ISSUE TITLE
Support latest cert-manager operator for openshift

### ISSUE THREAD

**Issue by gaohoward** [cert-manager/openshift-routes#39]
Currently the openshift-routes depends on cert-manager v1.8.0. However the latest OCP 4 has cert-manager v1.11.4.
It should be updated to be align with openshift. And it should be bundled with each openshift versions.
Users should be able to install a matching version of openshift route from operator-hub.

**Comment by ctrought** [comment]
I think openshift-routes will work with fine with cert-manager > v1.8.0, but it won't necessarily support new features or APIs added in newer versions of cert-manager. There are a couple PRs in progress that do upgrade the CMAPI used in openshift routes to use v1.12.X #29 #28

I would agree it would be very nice to have this packaged in a helm chart and/or OLM so end users can use these familiar tools as a mechanism to install, upgrade, and manage dependencies since there are multiple operators involved and as you mentioned may come from different sources. Installing via OperatorHub is common for OpenShift users as it's integrated directly in the console and OLM is available by default.

**Comment by gaohoward** [comment]
@ctrought Thanks you !

**Comment by maelvls** [comment]
@ctrought Agreed, a Helm chart and an OLM package would be great. I don't think the static manifest doesn't match what folks on OpenShift expect. I'd love to see Red Hat help in bundling openshift-routes! 😇

**Comment by inteon** [comment]
We now have a Helm chart and test openshift-routes with the latest version of cert-manager!
